### ISSUE TITLE
Figure out why enforceMarketclosure is being set to false when it should be true.

### ISSUE THREAD

**Issue by jcarroll2007** [bpeterman/FreeTrade#11]

**Comment by bpeterman** [comment]
I think I may have actually still had a line in the code that caused this to go to false.

**Comment by bpeterman** [comment]
https://github.com/bpeterman/FreeTrade/commit/4066054ec5b73102d91d04157e71550cdd74da64#diff-b4b043677933e9208b9f70b84f00e4d0
This may have been it.  Idk.  You posted this after I fixed it.  Your branch might not have been in sync with the master branch at that point.

**Comment by jcarroll2007** [comment]
Ok, cool. Thanks.
