### ISSUE TITLE
Some exceptions related to search on the Trade Tab

### ISSUE THREAD

**Issue by bpeterman** [bpeterman/FreeTrade#12]
When running the app executable outside of the debug directory there are exceptions with search.  The cause of this is the stocks csv files are not present.

Is there some way we can integrate these into the executable?

**Comment by jcarroll2007** [comment]
I'll work on this some tomorrow.

**Comment by bpeterman** [comment]
I'm not worried about this issue.  With finals coming up I think we'll disregard this.
