### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by jcarroll2007** [bpeterman/FreeTrade#13]
The professor wants reports. So, we could do monthly reports, where we get the price of each stock at the beginning of the month and determine how the user is doing compared to that date. Or we could just generate a report that shows an overall summary of everything for that user.

The later would be easy, so if we decide to go with the first option, we could potentially do both.

**Comment by bpeterman** [comment]
Let's go with the Easy option.  For some reason I think he is just set on every group having some sort of report.
