### ISSUE TITLE
Function Returns Null Results on time out.

### ISSUE THREAD

**Issue by bcamadin** [bpeterman/FreeTrade#22]
https://github.com/bpeterman/FreeTrade/blob/master/FreeTradeWindowsForms/FreeTradeWindowsForms/Stock.cs#L57

Is there away to retry 3 times then fail gracefully?

**Comment by bpeterman** [comment]
It now tries 3 times and if it can't reach Yahoo after the 3rd time it prompts the user then closes the application.
